[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."

[[redirects]]
  from = "/stock"
  to = "/index.html#stock"
  status = 200

[[redirects]]
  from = "/stock.html"
  to = "/index.html#stock"
  status = 200
